"""Generate docs/configuration.md from the settings metadata in eye_tracker.config.

Usage:
    uv run python scripts/gen_config_docs.py          # rewrite the page
    uv run python scripts/gen_config_docs.py --check  # exit 1 if the page is out of date

The output does not depend on the platform it is generated on (hotkey defaults
are listed for every platform), so CI can check it anywhere.
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from eye_tracker import config  # noqa: E402

OUTPUT = ROOT / "docs" / "configuration.md"

SECTION_TITLES = {
    "general": "General",
    "camera": "Camera",
    "performance": "Performance",
    "switching": "Switching",
    "panes": "Split panes (experimental)",
    "windows": "Window focus (experimental)",
    "presence": "Walk-away (presence)",
    "privacy": "Privacy",
    "hotkeys": "Hotkeys",
    "learning": "Learning",
    "updates": "Updates",
    "ui": "Interface",
}

HEADER = """# Configuration reference

Every option can be changed in **Settings** (tray menu). They are stored in `settings.json`
([where](privacy.md#what-is-stored-and-where); `eye-tracker doctor` prints the exact path, see
[the command line](../README.md#command-line)). Unknown keys are ignored, missing keys use the
defaults below, and out-of-range values are clamped, so a hand-edited file can never stop the app
from starting.

A file that is not valid JSON at all (a missing comma or quote) is renamed to
`settings.json.corrupt`, and **every** setting returns to its default: the hotkeys, the walk-away
action, and also the finished setup assistant, so walking away only shows a notification until you
finish it again. Quit Eye Tracker, fix the file and rename it back to `settings.json`.

Files written by earlier versions are updated when they are loaded. For example, hotkeys that are
still at an earlier version's defaults move to today's defaults once; hotkeys you chose stay.

<!-- Generated by scripts/gen_config_docs.py from eye_tracker.config; do not edit by hand. -->
"""


def section_notes() -> dict[str, str]:
    """A paragraph under a section's heading, for what the rows alone do not say.

    The numbers come from the defaults, so the page cannot contradict them.
    """
    presence = config.PresenceSettings()
    countdown_starts = presence.away_timeout_s - presence.warning_s
    example = config.HotkeySettings().toggle_tracking
    panes = config.PaneSettings()
    pane_example = max(panes.precision * 120, panes.min_pane_px)
    return {
        "panes": (
            "Off by default. Pane focus follows only on the monitor the cursor is already on, "
            f"at the earliest {panes.after_monitor_switch_ms} ms after a monitor switch, and the "
            "mouse grace of the switching settings applies too. A pane takes part when it is "
            "at least `precision` times the calibration's gaze error and at least "
            "`min_pane_px` wide (panes side by side) or tall (stacked panes): with the defaults "
            f"and a gaze error of 120 px that is {pane_example:.0f} px. Supported terminals and "
            "the full rules: [split-pane focus](panes.md)."
        ),
        "presence": (
            "The countdown is part of the away time: with the defaults it appears after "
            f"{countdown_starts} s without you, and the action follows at "
            f"{presence.away_timeout_s} s. Until the setup assistant is finished, `lock`, "
            "`display_off` and `lock_and_display_off` only show a notification. Walk-away "
            "detection needs the camera, so it pauses while tracking is paused, in privacy mode, "
            "during calibration and while another app has the camera."
        ),
        "hotkeys": (
            "A hotkey is written as modifiers and a key joined by `+`, in any case: `ctrl`, "
            "`alt`, `shift` and `meta` (the Windows key on Windows, Command ⌘ on macOS, Super on "
            f"Linux), for example `{example}`. An empty value turns that hotkey off. Wayland has "
            "no global hotkeys; see the [platform notes](platform-support.md#wayland)."
        ),
    }


def _code(value: Any) -> str:
    return f"`{value}`"


def _wrap(paragraph: str) -> str:
    """A paragraph wrapped like the hand-written pages (100 columns)."""
    return textwrap.fill(paragraph, width=100, break_long_words=False, break_on_hyphens=False)


def _default(key: str, value: Any) -> str:
    if key.startswith("hotkeys.") and isinstance(value, str) and "+" in value:
        # The default hotkeys are per platform (config._HOTKEY_MODIFIERS); list
        # each platform only while they differ.
        letter = value.rsplit("+", 1)[1]
        platforms = [
            ("Windows", config._HOTKEY_MODIFIERS.get("win32", config._HOTKEY_MODIFIERS_OTHER)),
            ("macOS", config._HOTKEY_MODIFIERS.get("darwin", config._HOTKEY_MODIFIERS_OTHER)),
            ("Linux", config._HOTKEY_MODIFIERS_OTHER),
        ]
        if len({mods for _name, mods in platforms}) == 1:
            return _code(f"{platforms[0][1]}+{letter}")
        return "<br>".join(f"{_code(f'{mods}+{letter}')} {name}" for name, mods in platforms)
    if isinstance(value, bool):
        return _code("true" if value else "false")
    if isinstance(value, list):
        return _code(", ".join(value)) if value else _code("[]")
    return _code(value)


def _allowed(row: dict[str, Any]) -> str:
    if row["choices"]:
        return " · ".join(_code(c) for c in row["choices"])
    lo, hi = row["lo"], row["hi"]
    if lo is None and hi is None:
        return ""

    def num(v: float) -> str:
        return str(int(v)) if float(v).is_integer() else str(v)

    return f"{num(lo)} – {num(hi)}"


def render() -> str:
    lines = [HEADER]
    notes = section_notes()
    current = None
    for row in config.describe_settings():
        section = row["key"].split(".", 1)[0]
        if section != current:
            current = section
            lines.append(f"\n## {SECTION_TITLES.get(section, section.title())}\n")
            if section in notes:
                lines.append(_wrap(notes[section]) + "\n")
            lines += ["| Key | Default | Allowed | Description |", "|---|---|---|---|"]
        doc = " ".join(str(row["doc"] or "").split()).replace("|", "\\|")
        lines.append(
            f"| {_code(row['key'])} | {_default(row['key'], row['default'])} "
            f"| {_allowed(row)} | {doc} |"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the page is out of date")
    args = parser.parse_args(argv)
    text = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print("docs/configuration.md is out of date; run scripts/gen_config_docs.py")
            return 1
        print("docs/configuration.md is up to date")
        return 0
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
